import { describe, expect, it } from "vitest";
import { extractGraphiqDsl } from "./extractGraphiqDsl.js";

const CLASS_DSL = `diagram class ImportTest

class Alpha {
}

class Beta {
}

Alpha --|> Beta`;

describe("extractGraphiqDsl", () => {
  it("returns the whole file when it starts with diagram and a legal kind", () => {
    const result = extractGraphiqDsl(`${CLASS_DSL}\n`);
    expect(result).toEqual({ kind: "class", dsl: CLASS_DSL });
  });

  it("strips a UTF-8 BOM and leading whitespace", () => {
    const result = extractGraphiqDsl(`\uFEFF\n  ${CLASS_DSL}\n`);
    expect(result).toEqual({ kind: "class", dsl: CLASS_DSL });
  });

  it("extracts the first fenced block after prose", () => {
    const result = extractGraphiqDsl(`# Generated by an LLM

Here is your diagram:

\`\`\`text
${CLASS_DSL}
\`\`\`
`);
    expect(result).toEqual({ kind: "class", dsl: CLASS_DSL });
  });

  it("extracts an unfenced diagram region after markdown", () => {
    const result = extractGraphiqDsl(`Some notes above.

${CLASS_DSL}
`);
    expect(result).toEqual({ kind: "class", dsl: CLASS_DSL });
  });

  it("returns the first valid fenced block when several exist", () => {
    const activityDsl = `diagram activity Flow

initial --> final
`;
    const result = extractGraphiqDsl(`\`\`\`
classDiagram
  A --> B
\`\`\`

\`\`\`text
${activityDsl}
\`\`\`
`);
    expect(result).toEqual({ kind: "activity", dsl: activityDsl.trim() });
  });

  it("returns null for Mermaid classDiagram text", () => {
    expect(
      extractGraphiqDsl(`classDiagram
  Order --> LineItem
`),
    ).toBeNull();
  });

  it("returns null for empty or prose-only files", () => {
    expect(extractGraphiqDsl("")).toBeNull();
    expect(extractGraphiqDsl("Just some notes about UML.")).toBeNull();
  });

  it("returns null for diagram with an invented kind", () => {
    expect(extractGraphiqDsl("diagram flowchart\nnode A\n")).toBeNull();
  });
});
