export const ELEMENT_TYPES = [
  "class",
  "interface",
  "dataType",
  "enumeration",
  "primitiveType",
  "associationClass",
  "note",
  "constraint",
  "instanceSpecification",
  "package",
  "part",
  "port",
  "collaboration",
  "collaborationUse",
  "component",
  "artifact",
  "node",
  "device",
  "executionEnvironment",
  "deploymentSpecification",
  "profile",
  "stereotype",
  "metaclass",
  "actor",
  "useCase",
  "subject",
  "activity",
  "action",
  "objectNode",
  "initialNode",
  "activityFinalNode",
  "flowFinalNode",
  "decisionNode",
  "mergeNode",
  "forkNode",
  "joinNode",
  "activityPartition",
  "interruptibleActivityRegion",
  "stateMachine",
  "region",
  "state",
  "pseudostate",
  "finalState",
  "interaction",
  "lifeline",
  "executionSpecification",
  "combinedFragment",
  "interactionUse",
  "gate",
  "destructionOccurrence",
  "stateInvariant",
  "timingState",
  "durationConstraint",
  "timeConstraint",
] as const;

export type ElementType = (typeof ELEMENT_TYPES)[number];

const elementTypeSet = new Set<string>(ELEMENT_TYPES);

export function isElementType(value: string): value is ElementType {
  return elementTypeSet.has(value);
}
